# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-09 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='email',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
